apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-datetime
  name: python-datetime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-datetime
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-datetime
    spec:
      containers:
      - image: mohammadrezaqaderi/time-zone:1.2
        name: python-datetime
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: /app/config/config.json
            subPath: config.json
            name: config-map
            readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: python-datetime
status: {}
